GET http://localhost:3000/users/ttt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImpvaG4xQGV4YW1wbGUuY29tIiwiaWQiOiJiOGVjOTdmMC02ZTUxLoQ4MjYtOThmOC01MjczZjE5MTM0NjciLCJpYXQiOjE3NjUwMjYxMTcsImV4cCI6MTc2NTExMjUxN30.Qy2VWNiA_oBmUIADAL_BkDKHcjpnqawif0hfP-GXg38